### ISSUE TITLE
Train Time Calculation Clarification

### ISSUE THREAD

**Issue by Ryan-Vereque** [tobias-kirschstein/gghead#11]
In the paper during the primary discussed training procedure, was the train time per-batch (which was batch-size of 32) closer to 127.78 ms or that value times 32 ?

**Comment by tobias-kirschstein** [comment]
This depends a bit on your specific hardware. The numbers in the paper were conducted on an A6000 GPU (48GB) with a batch size of 8 to be comparable for all methods. In that setting, it took on average 127.78 ms per train image for both forward and backward pass. Multiplying it by 32 to get the time for a batch size of 32 would not be quite correct, because you get more synergy effects for larger batch sizes, potentially reducing the average time per image. 
For example, training with a batch size of 32 (instead of 8) on a single A6000 takes roughly ~95ms per train image, or equivalently, ~3s per batch of 32 images.
