### ISSUE TITLE
Use template mesh on AFHQ datset?

### ISSUE THREAD

**Issue by SeriouslyWhite** [tobias-kirschstein/gghead#13]
Perfect work, how to explain the use of template mesh on cat head?

**Comment by tobias-kirschstein** [comment]
The purpose of the mesh is just to provide a rough initialization and to have a target for regularizing the Gaussians' positions. As we show in the ablations, you may also use other types of template meshes such as spheres or planes. We found the face mesh to work slightly better that's why we sticked to it. Presumably because it allocates more Gaussians in critical areas like the eyes and mouth which are regions that the discriminator pay special attention to. One can probably improve results slightly by using even better template meshes for faces / cats
