### ISSUE TITLE
Relationship between a Gaussian Map pixel Count and a Gaussian Count

### ISSUE THREAD

**Issue by Ryan-Vereque** [tobias-kirschstein/gghead#9]
In your the paper's ablation study on gaussian count, it includes counts for presumably 256^2 and 512^2 Gaussians.

How do things work when 256^2 Gaussians are used when the resolution of the Gaussian Maps is 512 ?

**Comment by tobias-kirschstein** [comment]
This is essentially just using the `grid_sample()` operator of PyTorch, i.e., for each query point (Gaussian) in UV space, it performs bilinear interpolation between the 4 neighboring texels. If the gaussian map resolution is larger than the sampling density that is not apriori an issue, it just means that neighboring Gaussians become less correlated. If the gaussian map resolution is much larger than the sampling density, you are essentially wasting compute since some texels are never sampled.
